### ISSUE TITLE
DNS cache of host names

### ISSUE THREAD

**Issue by HQuest** [troglobit/sysklogd#15]
Any chance the syslogd could cache DNS queries for remote hosts sending down messages? For busy logging systems, this puts an un-necessary load on the DNS server by triggering a new PTR query for every received message, and while adding the hostname on the hosts file, this defeats the purpose of having a DNS available (plus increases maintenance as multiple hosts files now needs update, versus a single location)

**Comment by troglobit** [comment]
Not sure we should attempt such black magic in syslogd.  Usually you set up a caching resolver using NSS in GLIBC, for instance dnsmasq can be used for this.  More info [here](https://wiki.archlinux.org/index.php/Domain_name_resolution#Glibc_resolver) and [here](https://stackoverflow.com/questions/11020027/dns-caching-in-linux).

**Comment by HQuest** [comment]
GLIBC resolver does not cache. Setting up a caching resolver also only does half of the job, since queries still have to hit the caching resolver every time - which still causes the DNS to log every single query versus new queries from still unknown/expired entries. Regardless, worth a shot. If you ever feel like this could be doable, it would be appreciated.

**Comment by troglobit** [comment]
Yes, that is what I meant by referring to dnsmasq, it's a caching proxy that does this well. Having read up on this some more, I'm now pretty convinced we should not try to do this in sysklogd. The only way any such functionality will get merged is if the BSD syslogd cousins gain some functionality wrt this.
