### ISSUE TITLE
syslogd under linux terminates with SIGPIPE with a small log buffer

### ISSUE THREAD

**Issue by ChrisVine** [troglobit/sysklogd#26]
If the kernel's log buffer is on the small side (certainly if CONFIG_LOG_BUF_SHIFT is 15 or less) then on boot up of a reasonably standard linux kernel, syslogd will terminate with a broken pipe error (presumably SIGPIPE).  This arose with the adoption of /dev/kmsg instead of /proc/kmsg and seems to indicate a timing problem respecting the slackware scripts which start syslogd - this is not a systemd boot-up.

Reverting commit 5aa7372f4ce8c49c7cf9e0994474c1a817b4d809 resolves the issue.

There is more about it here: https://www.linuxquestions.org/questions/slackware-14/syslogd-problem-with-sysklogd-2-2-0-a-4175688968/

**Comment by troglobit** [comment]
Interesting, sysklogd should of course not terminate because of this.  I assume the syslogd service starts very early?   I'll look into it, however, reverting to /proc/kmsg is not an option for the project.

Also, could you post the exact error message? It would help a great deal to help narrow down the problem.

**Comment by ChrisVine** [comment]
On the error message, all you get is syslogd printing to slackware's /var/log/syslog the message `syslogd[pid]: klog read(): Broken pipe` and then terminating.

From this I have presumed that this is a consequence of a SIGPIPE signal, and SIGPIPE is not set to be ignored (that is, write does not return with EPIPE).

**Comment by ChrisVine** [comment]
By the way, on the question of earliness, the slackware scripts are based on a non-standard SysV init with a BSD flavour.  The scripts start syslogd in /etc/rc.d/rc.syslog which is called up in /etc/rc.d/rc.M.  /etc/rc.d/rc.M is executed by init on a standard run-level multi-user boot (see /etc/inittab).

At heart lies a timing issue: you can always restart syslogd correctly from a terminal after boot-up.

**Comment by troglobit** [comment]
Thanks, googling a bit turns out this article on <https://lwn.net/Articles/490690/>, the relevant section quoted below (my emphasis added):

> - Support for multiple concurrent readers of `/dev/kmsg`, with `read()`,
>  `seek()`, `poll()` support. Output of message sequence numbers, to allow
>  userspace log consumers to reliably reconnect and reconstruct their
>  state at any given time. After `open("/dev/kmsg")`, `read()` always
>  returns *all* buffered records. If only future messages should be
>  read, `SEEK_END` can be used. **In case records get overwritten while
>  `/dev/kmsg` is held open, or records get faster overwritten than they
>  are read, the next read() will return `-EPIPE`** and the current reading
>  position gets updated to the next available record. The passed
>  sequence numbers allow the log consumer to calculate the amount of
>  lost messages.

Since we actually do get the `EPIPE` message (the `klog read() ...` is from sysklogd itself), then we can handle it.  I propose adding an extra line to the log file, e.g. "Kernel log buffer filling up too quick, adjust kernel CONFIG_LOG_BUF_SHIFT, or start syslogd earlier.", and then continue reading.

**Comment by ChrisVine** [comment]
Interesting.  If EPIPE is being set then I wonder what is killing syslogd?  Logging the problem (and that there may be lost data) is one thing; killing the syslogd process entirely is something else.

**Comment by troglobit** [comment]
Dunno atm, that could be another bug, or a system malfunction maybe.  I'll try to find some time to reproduce this and maybe learn more.  Please let me know if you find anything else

**Comment by ChrisVine** [comment]
I can reproduce this on two computers, one 64-bit and one 32-bit, and can verify that it only occurs when /dev/kmsg is enabled.  I suppose one way to debug this at leisure is to compile a kernel with a small CONFIG_LOG_BUF_SHIFT value and after boot up to hammer syslogd to provoke overruns (and so EPIPEs) to see what breaks.  Beyond that I am out of ideas.

It could of course be a kernel bug (I have only tested kernel 5.10.9) but that seems improbable.

**Comment by troglobit** [comment]
I'm setting up a test system now, using buildroot, with a smaller CONFIG_LOG_BUF_SHIFT to see if I can reproduce.
Could you perhaps attach your `/etc/syslog.conf`, or at least relevant parts?

I don't think this is a kernel bug, I'll be testing with a 5.10.x kernel as well.

**Comment by troglobit** [comment]
Reproduced, finally!  Had to add a LOT of kernel debug to trigger this in the otherwise calm and quiet Qemu env.

**Comment by ChrisVine** [comment]
Great.  My syslog.conf is vanilla, as supplied by slackware-current, as below:

```
# /etc/syslog.conf
# For info about the format of this file, see "man syslog.conf"
# and /usr/doc/sysklogd/README.linux. Note the '-' prefixing some
# of these entries; this omits syncing the file after every logging.
# In the event of a crash, some log information might be lost, so
# if this is a concern to you then you might want to remove the '-'.
# Be advised this will cause a performance loss if you're using
# programs that do heavy logging.

# Uncomment to see kernel messages 'err' or higher on the console.
# Note that this is disabled by default because the kernel has defined
# the "No irq handler for vector" message as 'emerg' (the highest, your
# system should be considered unusable) level and will spam the console
# during boot. But perhaps you can live with that in order to see the
# other kernel messages...
#kern.err                                               /dev/console

# Log anything 'info' or higher, but lower than 'warn'.
# Exclude authpriv, cron, mail, and news. These are logged elsewhere.
*.info;*.!warn;\
        authpriv.none;cron.none;mail.none;news.none     -/var/log/messages

# Log anything 'warn' or higher.
# Exclude authpriv, cron, mail, and news. These are logged elsewhere.
*.warn;\
        authpriv.none;cron.none;mail.none;news.none     -/var/log/syslog

# Debugging information is logged here:
*.=debug                                                -/var/log/debug

# Private authentication message logging:
authpriv.*                                              -/var/log/secure

# Cron related logs:
cron.*                                                  -/var/log/cron

# Mail related logs:
mail.*                                                  -/var/log/maillog

# Emergency level messages go to all users:
*.emerg                                                 *

# Uncomment to log news and uucp errors:
#uucp,news.crit                                         -/var/log/spooler

# Uncomment these if you run a news server and would like to log related
# messages:
#news.=crit                                     -/var/log/news/news.crit
#news.=err                                      -/var/log/news/news.err
#news.notice                                    -/var/log/news/news.notice

# Include all config files in /etc/syslog.d/:
include /etc/syslog.d/*.conf
```

/etc/syslog.d is empty.

**Comment by troglobit** [comment]
Great, thank you! :)

**Comment by troglobit** [comment]
I believe this is fixed now.  I've added detection for `EPIPE` and verified the resulting code, unfortunately there is no support yet for showing how many `printk()`'s were lost.  This will go into a v2.2.1 release that'll likely be out soonish (read: next weekend at the latest).

If you can, I'd very much appreciate more ppl testing the fix.  The GIT hash can be downloaded as a patch like this:

   <https://github.com/troglobit/sysklogd/commit/3e4000b.patch>

Cheers
 /Joachim

**Comment by ChrisVine** [comment]
I confirm that this fixes it for me.

So it was SIGPIPE after all, but at one remove, caused by the closing of the socket where the /dev/kmsg read set EPIPE.

**Comment by troglobit** [comment]
Cool, that's great news!  Thank you for taking the time to report this and helping out nailing it down! <3
