### ISSUE TITLE
syslog ignore selector (!=) not working

### ISSUE THREAD

**Issue by denydias** [troglobit/sysklogd#27]
Hi there! Slackware user here.

After a [limited success in downstream realm](https://www.linuxquestions.org/questions/showthread.php?p=6211692#post6211692), I now come here asking for further assistance with the issue bellow.

I have the following rule on my netfilter based script:

```
LOG all -- anywhere anywhere LOG level warning prefix "RULE 7 -- DENY "
```

My `/etc/syslog.conf` have this rule:

```
# Log anything 'warn' or higher.
# Exclude netfilter, authpriv, cron, mail, and news. These are logged elsewhere.
*.warn;kern.!=warn;\
  authpriv.none;cron.none;mail.none;news.none -/var/log/syslog
```

This used to work fine so netfilter messages (`kern.warning`) won't be logged to `/var/log/syslog`.  Since Slackware -current `Mon Jan 18 13:50:16 UTC 2021` changelog, when sysklogd was updated to 2.2.0, I noted that these warning messages are back in `/var/log/syslog`.

`kern.none` (no kernel messages at all) and `kern.!warn` (no kernel warns and above) both works as expected, but `kern.!=warn` 
 don't (negate kernel warn level only).

I've already read all `man syslog.conf`, checked all the syslog rules and issues here, but I failed to found a way to get those `kern.warning` messages out of `/var/log/syslog`.

As [proposed by a fellow Slackware user](https://www.linuxquestions.org/questions/slackware-14/syslog-ignore-rules-not-working-4175689199/#post6211665), the following rule work with limitations (i.e. do not log any `kern.*`):

```
*.warn;kern.none;kern.!=warn
```

So I'm here to report this issue, as it was already confirmed by others in downstream discussion.

Thanks in advance.

**Comment by troglobit** [comment]
Hi, thank you for your report!

Am I reading the Slackware logs¹ correctly, was the previous version v1.5.1 (with local Slackware patches) in Slackware, before upgrading to v2.2.0?  If so, that's a big leap and quite a bit of ground to cover to track this one down.

I'll have to look into this later tonight, or the coming weekend.

**Comment by denydias** [comment]
Hi @troglobit! Thank your for your quick reply.

I don't know what changelog you were reading (the superscript note came without a link in your comment), but it looks you're referring to [Slackware 14.2 (stable)](http://www.slackware.com/changelog/stable.php?cpu=x86_64) one. In that branch, sysklogd version is indeed 1.5.1.

Fortunately the leap is not that big as I'm referring to [Slackware -current](http://www.slackware.com/changelog/current.php?cpu=x86_64), the development branch. There sysklogd is 2.2.0 since `Mon Jan 18 13:50:16 UTC 2021`, which replaced sysklogd-2.1.2 added in `Wed Dec 23 21:21:34 UTC 2020`.

I appreciate your review of this issue. Take your time and if can be of any assistance, don't hesitate reach me here.

**Comment by troglobit** [comment]
Aha, trying to understand the dev prices of Slackware. Last time I used this great dist was back in the 90's :)

So, you're saying your setup worked with v2.1.2?  That would help a great deal of true :)

**Comment by denydias** [comment]
Cool! I use it since mid 90's! :wink: 

Yes. It was working fine on v.2.1.2, then the issue came with v2.2.0.

**Comment by troglobit** [comment]
Awesome!  I also fondly remember the Slax LiveCD, used them a lot :)

Great feedback!  I'll see what I can find later tonight (CET).  A quick glance at the diff [v2.1.2..v2.2.0](https://github.com/troglobit/sysklogd/compare/v2.1.2...v2.2.0) doesn't show any obvious candidates ... I'll see what I can find and if I can reproduce it.

**Comment by denydias** [comment]
Yes, I did a diff on that too and found no obvious cause! :(

Thank you so much, @troglobit. I'm reading you blog now if I may! Your first password at Henrik’s... LOL!

Cheers from Brazil!

**Comment by troglobit** [comment]
Tried reproducing with the following, using the mail subsystem, to see if it's a .conf parser problem

```
*.warn;mail.!=warn;\
  authpriv.none;cron.none;mail.none;news.none -/var/log/foo
```

Unfortunately that works just fine.  `logger -p mail.warn "foobar"` is *not* written to /var/log/foo, but `-p mail.err` and other levels do.  As it should.  

So I'm worried this might be caused by, or related to, the change from using /proc/kmsg to /dev/kmesg, which was done in v2.2.0.  To verify that, I need to create a dedicated kernel module that generates log patterns for me to test.   Obviously that'll take me a while, sorry :worried:

**Comment by troglobit** [comment]
There, reproduced!

**Comment by troglobit** [comment]
Aaaand fixed! :smiley::vulcan_salute:  

The v2.2.1 release will likely be made during the upcoming weekend (probably Saturday).  Until then you can use the following patch, if you want to rebuild the package:

https://github.com/troglobit/sysklogd/commit/d2444c7.patch

Thank you so much for taking the time to report and help out localizing this bug! :heart:

**Comment by denydias** [comment]
That was fast!

I'll apply the patch and recompile it later today. I get back to you soon.

Thank you so much, @troglobit. I'm impressed by your responsivity!

**Comment by denydias** [comment]
I've just recompiled sysklogd-2.2.0 with the provided patch.

> Until then you can use the following patch, if you want to rebuild the package:
> https://github.com/troglobit/sysklogd/commit/d2444c7.patch

I can confirm it worked like a charm! `*.warn;kern.!=warn` now filter out only `kern.warn` messages where it was applied.

Thanks so much for the quick patch, @troglobit! \o/

**Comment by troglobit** [comment]
Great to hear! :smiley: 

No problem, this project is a bit of high prio for me right now.  So this week I'm fast-tracking all related issues.  We use it at $DAYJOB *and* I also want to see a stable version in the upcoming Buildroot LTS.

Take care!
