### ISSUE TITLE
last message buffered x times

### ISSUE THREAD

**Issue by DocMAX** [troglobit/sysklogd#30]
is it possible to disable this message?

**Comment by troglobit** [comment]
Nope, but you can patch it locally of course.

**Comment by DocMAX** [comment]
hmm, i'm not a coder :-(. but could you change it to:
`date hostname **app_name** last message buffered x times`
or at least give me a patch file? thank you!!

**Comment by troglobit** [comment]
I'm sorry, but this is not a wishing well, and I have no need for this myself (or $DAYJOB).

**Comment by DocMAX** [comment]
ok switched to syslog-ng

**Comment by opty77** [comment]
@DocMAX: Fixed by #61 now?

@troglobit: Remove https://github.com/troglobit/sysklogd/labels/wontfix?

**Comment by DocMAX** [comment]
I don't remember what i was talking about.

**Comment by troglobit** [comment]
Ah yes, this has been fixed now since it turned out to be a regression in v2.0.
