### ISSUE TITLE
Invalid time for kernel messages on 32-bit machines (x86)

### ISSUE THREAD

**Issue by dale-email** [troglobit/sysklogd#31]
Hi,

I've got a machine running 32 bit x86 Linux and was wondering why I was getting invalid times for logged kernel messages with sysklogd-2.2.2.
It appears that suseconds_t used in struct logtime which in turn is used in struct buf_msg is only 32 bit on my machine.
Unfortunately in printsys() in syslogd.c, buffer.timestamp.usec (of type suseconds_t) is used when interpreting how many microseconds the machine has been up and this will fail if the machine has been up for more than 2^31 us (=2147 sec) or 2^32 us (=4294 sec) depending on whether suseconds_t is signed (I haven't checked).
I think the interpretation of the kernel log line timestamp (microseconds since boot) needs to be done with a variable guaranteed to be 64bit e.g. uint64_t, something like:

void printsys(char *msg)
{
        struct buf_msg buffer;
        char line[MAXLINE + 1];
        uint64_t seqno = 0;
        uint64_t ustime = 0;                                                               /* NEW VARIABLE */
        char *lp, *p, *q;
        int c;

        lp = line;
        for (p = msg; *p != '\0';) {
                memset(&buffer, 0, sizeof(buffer));
                buffer.app_name = "kernel";
                buffer.hostname = LocalHostName;
                buffer.pri = DEFSPRI;
                buffer.msg = line;

                if (*p == '<') {
                        /* /proc/klog or *BSD /dev/klog */
                        buffer.pri = 0;
                        while (isdigit(*++p))
                                buffer.pri = 10 * buffer.pri + (*p - '0');
                        if (*p == '>')
                                ++p;
                } else if (isdigit(*p)) {
                        /* Linux /dev/kmsg: "pri,seq#,msec,flag[,..];msg" */
                        time_t now = boot_time;

                        /* pri */
                        buffer.pri = 0;
                        while (isdigit(*p))
                                buffer.pri = 10 * buffer.pri + (*p++ - '0');

                        p++;          /* skip ',' */

                        /* seq# */
                        while (isdigit(*p))
                                seqno = 10 * seqno + (*p++ - '0');

                        p++;          /* skip ',' */

                        /* timestamp */
                        while (isdigit(*p))
                                ustime = 10 * ustime + (*p++ - '0');               /* UPDATED */
                        now += ustime / 1000000;                                     /* UPDATED */
                        buffer.timestamp.usec = ustime % 1000000;         /* UPDATED */
                        localtime_r(&now, &buffer.timestamp.tm);
(...)

Changes in the above marked with comments - sorry for not providing a diff but its only four lines of changes.

Testing suggests that the above changes fix the issue,

Best Regards,

Dale.

**Comment by troglobit** [comment]
Interesting, this may very well be related to #28, which I got reported to me from Slackware.  I'll have a look at this over the weekend to see what I can do.  Your suggestion looks like the obvious starting point, so thank you for that!
