### ISSUE TITLE
sysklogd version 2.0.1: klogd.8 missing

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#4]
the source tarball does not contain the man-page for klogd which breaks the build/install if klogd is enabled

**Comment by troglobit** [comment]
Ouch, my build tree was configured `--without-klogd`.  Fortunately I can fix this with a new upload without doing a new release (unlike the other issues you've just posted).

**Comment by troglobit** [comment]
Fixed with new upload.
