### ISSUE TITLE
use of libsyslog

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#5]
I don't know if this is intentionally, but currently klogd is linked against the shared library libsyslog but syslogd is not?

**Comment by troglobit** [comment]
Ah, you've got a keen eye, sir!  However, libsyslog is a replacement API for syslog()/syslogp() family of APIs and thus only klogd needs to link against it.  syslogd itself has its own functions for appending to log files and sending to remote syslog servers.

Thanks for the report, closing! :smiley:
