### ISSUE TITLE
logging to remote machine stops after receiving a few SIGHUPs

### ISSUE THREAD

**Issue by meta-ed** [troglobit/sysklogd#56]
# Background
Log rotation using an external tool generally involves two steps. (1) rename the existing logs; (2) send SIGHUP to syslogd to create the new logs. For example, Slackware 15.0 has this logrotate(8) script:
```
/var/log/cron /var/log/debug /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler /var/log/syslog {
    sharedscripts
    missingok
    postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2>/dev/null` 2>/dev/null || true
    endscript
}
```
# Problem report
After several iterations of log rotation using SIGHUP, peers created using the @ symbol in syslog.conf stop receiving messages. Here is the example of such a peer that I used to reproduce the problem:
```
*.*                                                     @200.200.200.104        ;RFC3164
```
The communication failure is associated with frequent diagnostic messages logged by syslogd itself. Here is a log extract. (Please note these messages are pulled from /var/log/syslog and /var/log/messages and sorted by timestamp so might not be in exactly the correct order.)
```
Jul 17 04:40:01 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:40:01 slack syslogd[756]: Only 16 IP addresses per socket supported.
Jul 17 04:40:01 slack syslogd[756]: syslogd v2.4.0: restart.
Jul 17 04:43:01 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:43:01 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 04:46:00 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:46:00 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 04:49:14 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:49:14 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 04:52:17 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:52:17 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 04:55:23 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:55:23 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 04:58:24 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 04:58:24 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 05:01:25 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 05:01:25 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 05:04:25 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 05:04:25 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
Jul 17 05:07:25 slack syslogd[756]: INET sendto(200.200.200.104:syslog): Success
Jul 17 05:07:25 slack syslogd[756]: Successfully resolved '200.200.200.104:syslog', initiating forwarding.
```
# Possible root cause/resolution
Looking at the source to syslogd.c, the problem may be in `init()` which, when SIGHUP is received, closes all inet sockets but does not reset the socket count to 0, then reopens the sockets. So the pe_sock table fills up a little more after each SIGHUP until finally it is full and the socket cannot be reopened:
```
	SIMPLEQ_FOREACH(pe, &pqueue, pe_link) {
		if (pe->pe_name && pe->pe_name[0] == '/') {
			create_unix_socket(pe);
		} else {
			for (size_t i = 0; i < pe->pe_socknum; i++)
				socket_close(pe->pe_sock[i]);

			if (SecureMode < 2)
				create_inet_socket(pe);
		}
	}
```
If this is correct, the solution might be to add a line after the for loop:
```
                        pe->pe_socknum = 0;
```
Please, can someone having more familiarity with the socket management in syslogd.c review this bug report and let me know if there is more to it than this. After the review I will write the patch.

**Comment by troglobit** [comment]
Ouch, good find, and an awesome report, thank you!

Yes, this is indeed the root cause.  Functionality was introduced in v2.4.0 to support changing secure mode without having to stop+start the daemon, so bug is limited to this release, thankfully.

I can do the patch.

**Comment by troglobit** [comment]
There fixed.  I updated the `remote.sh` test as well to catch any future regressions to this (in the current implementation).

**Comment by meta-ed** [comment]
I confirm I can no longer reproduce the issue when running v2.4.1-pre.

**Comment by troglobit** [comment]
Awesome, thanks for double-checking @meta-ed :-)

Have you seen any other issues so far, or do you agree it's time to release v2.4.1?

**Comment by meta-ed** [comment]
I've had v2.4.1-pre live for about 24 hours, and have seen no other issues.

**Comment by troglobit** [comment]
Thank you, I'll start preparing a release in the next couple of days.
