### ISSUE TITLE
Minor: `syslogd.c` comments regarding kernel messages source

### ISSUE THREAD

**Issue by opty77** [troglobit/sysklogd#69]
`kernel_cb()` comment mentions just `/dev/klog` but I believe that it should contain also `/proc/kmsg` and `/dev/kmsg`.

`printsys()` comments use `/proc/klog` most probably instead of `/proc/kmsg`.

**Comment by troglobit** [comment]
This is *extremely* minor, and while on the topic of *minor issues*, I noticed you also spent time commenting on a misspelled commit message of mine, something I (ashamed and bitter) noticed muself when I wrote the changelog for that same release.  Not sure what you're after, but if you really care this much about that specific comment, why not just save us both a HUGE amount of time and just submit a pull-request with a change and this very issue text?

**Comment by opty77** [comment]
Unwanted help, sorry for bothering.
