### ISSUE TITLE
klogd: bogus error message

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#7]
At start of klogd I always get a bogus error message "Cannot find a map file." even though it seems that klogd  finds my map file at /boot/system.map just fine.

Here's the debug output:

 #> klogd -n -d -f /tmp/klogd.log
Logging line:
        Line: klogd v%s, log source = %s started.
        Priority: 6
Searching for symbol map.
Trying /boot/System.map-5.4.1.
Trying /boot/System.map.
Logging line:
        Line: Inspecting %s
        Priority: 6
No version information found.
Trying /System.map-5.4.1.
Trying /System.map.
Trying /usr/src/linux/System.map-5.4.1.
Trying /usr/src/linux/System.map.
End of search list encountered.
Logging line:
        Line: Cannot find a map file.
        Priority: 4
Cannot find a map file.
Loading kernel module symbols - Source: /proc/kallsyms
Logging line:
        Line: Loaded %d %s from %d module%s
        Priority: 6

and the content of /tmp/klogd.log:

 #> cat /tmp/klogd.log 
klogd v2.0.3, log source = /proc/kmsg started.
Inspecting /boot/System.map
Cannot find a map file.
Loaded 45119 symbols from 36 modules.

Thanks!

**Comment by troglobit** [comment]
ACK.

Note: klogd will likely be removed in an upcoming major release (2.1/2.2).

**Comment by troglobit** [comment]
klogd removed in 6bb6672
