### ISSUE TITLE
syslogd: kernel messages are always duplicated to console

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#8]
If we run syslogd standalone without klogd all kernel messages appears on a tty console too. This does not happen if we run syslogd together with klogd. This is very annoying if you start the system without a graphical login manager, because system startup messages are mixed up with kernel messages.

How to reproduce:
start syslogd and switch to a text console, trigger a kernel message 

System: CRUX linux

Thanks.

**Comment by troglobit** [comment]
What version of syslogd are you using now?

How did you run the `configure` script?  The only way for syslogd to run stand-alone in the v2.0 series is to build `--without-klogd` (default option), otherwise you *must* run klogd to collect kernel logs.  This behavior has been a part of the sysklogd since v1.3 or so.

**Comment by fjaell** [comment]
Here's how I configure version 2.0.3:

 ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --runstatedir=/var/run \
        --without-klogd \
        --without-logger \

To be clear, the kernel messages are send to the log-file, configured as /var/log/messages, but also duplicated to the text console.

**Comment by troglobit** [comment]
Thank you for the update and clarification, it really helps!

Could it be that you're using the example `syslog.conf` as default in CRUX?  It has the following line that is the likely root cause:

```
# Emergencies are sent to anyone logged in
#
*.=emerg                        *
```

We've removed that in our¹ system and I'm considering commenting it out in the shipped example as well.

**Comment by fjaell** [comment]
Yes, we have that line in our default `syslog.conf`. But I'm sorry to say that removing it doesn't help. 
For reference here's the config file we are using currently, see [syslog.conf](https://crux.nu/gitweb/?p=ports/core.git;a=blob;f=sysklogd/syslog.conf), but as I said removing the first rule has no effect.

**Comment by troglobit** [comment]
Huh, that's certainly odd!  We've been testing our build for a month now, and also have klogd disabled, but this phenomenon we haven't seen even once ... could you perhaps try running `syslogd -d -F -f foo.conf ...` and report back the findings?  Maybe syslogd somehow fails to open /var/log/kernel and reverts to using the console.

**Comment by fjaell** [comment]
I'm not able to paste the output directly, please look at https://342799c096e107f9.paste.se/
for what I get for:

`#> syslogd -d -F`

the output of

`#> syslogd -d -F -f foo.conf`

is here https://0c5322893a203372.paste.se/

**Comment by troglobit** [comment]
Interesting, there doesn't seem to be anything wrong with the defaults and fall-back to /dev/console using foo.conf seems to work as well.  Exceedingly odd this one ... :confused: 

Could you perhaps paste the kernel log messages you guys see so I can have a look at the format?  I'm curious exactly where and who does the actual leaking.

**Comment by troglobit** [comment]
OK, I've tried now to reproduce your issue in [TroglOS](https://github.com/troglobit/troglos) which is an extremely vanilla distro for embedded I've put together to test my various projects.  I used your syslog.conf but I cannot reproduce the issue, at-all. Terribly sorry!

Are you sure there isn't something else reading the kernel log, or the kernel being set up to write to console? (Dunno if this is even possible?)  

syslogd reads kernel log messages from `/proc/kmsg` ... maybe there's something there that you do differently? (Dunno what that could be either)

**Comment by fjaell** [comment]
The messages are the same but without the parts added by syslog, here's what I see on the text console after inserting an USB card reader:
`usb 6-2: New USB device found, idVendor=054c, idProduct=0c5d, bcdDevice= 0.06`

and here what got written to /var/log/kernel:
`Dec  6 08:47:32 jue kernel: usb 6-2: New USB device found, idVendor=054c, idProduct=0c5d, bcdDevice= 0.06`

It's strange that everything works fine if I use the combo syslogd/klogd, but the syslogd compiled for standalone use duplicates the messages.

**Comment by troglobit** [comment]
I think I understand now what's going on here.  When `klogd` runs it talks to the kernel to disable console logging using [klogctl(2)](https://linux.die.net/man/2/syslog), i.e. `SYSLOG_ACTION_CONSOLE_OFF`.  Current version of `syslogd` doesn't do that.

I suspect your system has the kernel configured to default to send logs to console.  We have the following in our `/etc/sysctl.conf`:

```
kernel.printk = 3 4 1 3
```

My Ubuntu system at work has the following:

```
joachim@troglobit:~$ sysctl kernel.printk
kernel.printk = 4	4	1	7
```

Try changing that to `3 4 1 3` and see if it helps.   In the meantime I'll look into adding support to syslogd to call `klogctl()` when running on Linux.

**Comment by fjaell** [comment]
Yeah, you found it, great ! Here's the default on my CRUX system: 

` # sysctl kernel.printk `
` kernel.printk = 7       4       1       7`

Setting 

` # sysctl kernel.printk="3 4 1 3"`
` kernel.printk = 3 4 1 3`

solved the issue. Many thanks!

**Comment by troglobit** [comment]
No problem, thank you for taking the time to report and help debug the issue! :)

Like I said, I'll go ahead and add support for calling `klogctl()` in syslogd for the next release.  I'll reference this issue with the fix-commit.
