### ISSUE TITLE
syslogd: kernel logging broken if started without the -F option

### ISSUE THREAD

**Issue by fjaell** [troglobit/sysklogd#9]
If I start syslogd without the -F option, meaning in the background, logging of kernel messages is broken and I get the following error message:

`Dec  7 11:56:24 jue syslogd[3431]: syslogd v2.0.3: restart`
`Dec  7 12:01:16 jue syslogd[3522]: klog read(): Bad file descriptor`

Running syslogd in the foreground works, I've tested the following:

`syslogd -F &`
`setsid syslogd -F`
`start-stop-daemon --start -bC --exec /usr/sbin/syslogd -- -F`

Thanks!

**Comment by troglobit** [comment]
Ah, thanks for the reminder!  Will look into it later today :+1:

**Comment by troglobit** [comment]
There, should be fixed now.  Seems to work on TroglOS when I test the fix(es) manually :)

**Comment by fjaell** [comment]
Yep, looks good, running 2.1-dev without any issues here. Many thanks again.
